load_module /home/sebastian/ideas/nginx/objs/ngx_http_luminawaf_module_asan.so;
events { worker_connections 1024; }
http {
    access_log off;
    server {
        listen 8085;
        lumina_waf on;
        location / {
            root html;
        }
    }
}
