load_module /home/sebastian/ideas/nginx/objs/ngx_http_luminawaf_module.so;
load_module /home/sebastian/ideas/nginx/objs/ngx_http_modsecurity_module.so;
events { worker_connections 1024; }
http {
    access_log off;
    server {
        listen 8085;
        lumina_waf on;
        location / {
            root html;
        }
        location /raw {
            alias html/;
            lumina_waf off;
        }
        location /modsec {
            alias html/;
            lumina_waf off;
            modsecurity on;
            modsecurity_rules_file /home/sebastian/workspace/lumina-waf/test_nginx/modsec/main.conf;
        }
    }
}
