load_module /home/sebastian/ideas/nginx/objs/ngx_http_luminawaf_module.so;
worker_processes auto;
pid /home/sebastian/workspace/lumina-waf/test_nginx/logs/nginx_lumina.pid;
events {
    worker_connections 4096;
}
http {
    access_log off;
    client_body_temp_path /home/sebastian/workspace/lumina-waf/test_nginx/tmp/client_body;
    proxy_temp_path /home/sebastian/workspace/lumina-waf/test_nginx/tmp/proxy;
    fastcgi_temp_path /home/sebastian/workspace/lumina-waf/test_nginx/tmp/fastcgi;
    uwsgi_temp_path /home/sebastian/workspace/lumina-waf/test_nginx/tmp/uwsgi;
    scgi_temp_path /home/sebastian/workspace/lumina-waf/test_nginx/tmp/scgi;
    
    server {
        listen 8081;
        lumina_waf on;
        location / {
            return 200 "OK\n";
        }
    }
}
