worker_processes auto;
events { worker_connections 4096; }

http {
    log_subrequest on;
    # Logging format for the main LuminaWAF request
    log_format lumina_log escape=json
      '{"time": "$time_iso8601", "req_id": "$request_id", "type": "lumina", '
      '"request": "$request", "status": $status, '
      '"latency": "$upstream_response_time"}';

    # Logging format for the mirrored ModSecurity request
    log_format modsec_log escape=json
      '{"time": "$time_iso8601", "req_id": "$request_id", "type": "modsec", '
      '"request": "$request", "status": $status, '
      '"latency": "$upstream_response_time"}';

    upstream lumina_backend {
        server lumina_waf:80;
    }

    upstream modsec_backend {
        server modsec_waf:8080;
    }

    server {
        listen 80;
        
        # We process the request on LuminaWAF but mirror it to ModSecurity.
        location / {
            mirror /mirror_modsec;
            mirror_request_body on;

            proxy_pass http://lumina_backend;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            
            access_log /var/log/nginx/access_real.log lumina_log;
        }

        # The mirror block that duplicates traffic
        location = /mirror_modsec {
            internal;
            proxy_pass http://modsec_backend$request_uri;
            proxy_pass_request_body on;
            proxy_set_header Host $host;
            proxy_set_header X-Mirror-Request "true";
            
            access_log /var/log/nginx/access_real.log modsec_log;
        }
    }
}
