#!/usr/bin/env python3
"""Emit src/generated/crs_rule_idx_map.h from rule_manifest.json.

The verdict slab is indexed by engine idx, while scanners return CRS rule IDs.
This generated table maps CRS id -> engine idx for every generated AOT rule.
Out-of-manifest IDs intentionally return -1 and use the hashed fallback path.
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
DEFAULT_MANIFEST = ROOT / "src/generated/rule_manifest.json"
DEFAULT_OUT = ROOT / "src/generated/crs_rule_idx_map.h"


def load_ids(manifest_path: Path) -> list[int]:
    manifest = json.loads(manifest_path.read_text(encoding="utf-8"))
    ids = [int(x) for x in manifest["generated_rule_ids"]]
    expected = int(manifest["short_rule_count"])
    if len(ids) != expected:
        raise SystemExit(f"manifest count mismatch: generated_rule_ids={len(ids)} short_rule_count={expected}")
    if len(set(ids)) != len(ids):
        raise SystemExit("manifest generated_rule_ids are not unique")
    return ids


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--manifest", default=str(DEFAULT_MANIFEST), help="translator rule manifest")
    parser.add_argument("--out", default=str(DEFAULT_OUT), help="output header path")
    args = parser.parse_args()

    manifest_path = Path(args.manifest)
    out = Path(args.out)
    ids = load_ids(manifest_path)
    pairs = sorted((rid, idx) for idx, rid in enumerate(ids))
    n = len(ids)

    lines: list[str] = []
    lines.append("/* AUTO-GENERATED by tools/gen_rule_idx_map.py. Do not edit. */")
    lines.append("#ifndef CRS_RULE_IDX_MAP_H")
    lines.append("#define CRS_RULE_IDX_MAP_H")
    lines.append("")
    lines.append(f"/* CRS rule id -> engine idx (0..{n - 1}) for the verdict slab.")
    lines.append(" * -1 == id is not one of the compiled short rules.")
    lines.append(" * Static binary search; AOT data, no runtime CRS parsing. */")
    lines.append("")
    lines.append(f"#define CRS_RULE_IDX_MAP_N {n}")
    lines.append("static const int g_rule_idx_id[CRS_RULE_IDX_MAP_N] = {")
    for i in range(0, n, 10):
        lines.append("    " + ",".join(str(rid) for rid, _ in pairs[i:i + 10]) + ",")
    lines.append("};")
    lines.append("static const int g_rule_idx_pos[CRS_RULE_IDX_MAP_N] = {")
    for i in range(0, n, 10):
        lines.append("    " + ",".join(str(idx) for _, idx in pairs[i:i + 10]) + ",")
    lines.append("};")
    lines.append("")
    lines.append("static inline int lumina_rule_id_to_engine_idx(int id) {")
    lines.append("    int lo = 0, hi = CRS_RULE_IDX_MAP_N - 1;")
    lines.append("    while (lo <= hi) {")
    lines.append("        int mid = (lo + hi) >> 1;")
    lines.append("        int v = g_rule_idx_id[mid];")
    lines.append("        if (v == id) return g_rule_idx_pos[mid];")
    lines.append("        if (v < id) lo = mid + 1; else hi = mid - 1;")
    lines.append("    }")
    lines.append("    return -1;")
    lines.append("}")
    lines.append("")
    lines.append("#endif /* CRS_RULE_IDX_MAP_H */")

    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"EMITTED {out}: {n} entries")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
